export const dataJson = [
    {
        number: "1",
        studentID: "53847",
        name: "ศรัณย์",
        sirname: "จารุกิจไพศาล",
        university: "มหาวิทยาลัยธรรมศาสตร์ ท่าพระจันทร์",
        faculty: "Faculty of Commerce and Accountancy",
        major: "Business Administration",
        "TCAS ": "1",
        course: "นานาชาติ",
        keywords: "อินเตอร์ BBA TU มธ. inter อินเตอร์ แบงค์ bank",
    },
    {
        number: "2",
        studentID: "54538",
        name: "อรัญญ์",
        sirname: "อัศวสืบสกุล",
        university: "จุฬาลงกรณ์มหาวิทยาลัย",
        faculty: "อักษรศาสตร์",
        major: "-",
        "TCAS ": "1",
        course: "ไทย",
        keywords: "ฟอร์ด ford CU chula",
    },
    {
        number: "3",
        studentID: "54542",
        name: "นิติธร",
        sirname: "ตรีสุรมงคลโชติ",
        university: "จุฬาลงกรณ์มหาวิทยาลัย",
        faculty: "อักษรศาสตร์",
        major: "-",
        "TCAS ": "3",
        course: "ไทย",
        keywords: "แซม sam CU chula",
    },
    {
        number: "4",
        studentID: "54546",
        name: "คทายุทธ์",
        sirname: "กรรณสูต",
        university: "จุฬาลงกรณ์มหาวิทยาลัย",
        faculty: "วิศวกรรมศาสตร์",
        major: "วิศวกรรมคอมพิวเตอร์",
        "TCAS ": "3",
        course: "ไทย",
        keywords: "เจด้า jda วิศวะ วิศวะคอม Chula CU",
    },
    {
        number: "5",
        studentID: "54622",
        name: "อธิพัชร์",
        sirname: "วราสินกุลภัทร์",
        university: "มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี",
        faculty: "วิศวกรรมศาสตร์",
        major: "วิศวกรรมเครื่องกล",
        "TCAS ": "1",
        course: "ไทย",
        keywords: "อาโนลด์ arnold วิศวะ มจธ. บางมด kmutt",
    },
    {
        number: "6",
        studentID: "54624",
        name: "อภิวิชญ์",
        sirname: "วนิชธัญญาทรัพย์",
        university: "มหาลัยเกษตรศาสตร์",
        faculty: "วิศวกรรมศาสตร์",
        major: "วิศวกรรมไฟฟ้า",
        "TCAS ": "3",
        course: "ไทย",
        keywords: "ไซแอนท์ science วิศวะ มก. KU วิศวะไฟฟ้า",
    },
    {
        number: "7",
        studentID: "54625",
        name: "สัจจพล",
        sirname: "สุคตะ",
        university: "มหาวิทยาลัยนวมินทราธิราช",
        faculty: "แพทยศาสตร์",
        major: "วชิรพยาบาล - โรงพยาบาลตากสิน",
        "TCAS ": "3",
        course: "ไทย",
        keywords: "ฮิมต้า himta แพทย์ วพม. PCM หมอ เเพทยศาสตร์ เเพทย์",
    },
    {
        number: "8",
        studentID: "54630",
        name: "กฤตติพัฒน์",
        sirname: "วงค์สาโรจน์",
        university: "มหาวิทยาลัยธรรมศาสตร์ ศูนย์รังสิต",
        faculty: "นิติศาสตร์",
        major: "-",
        "TCAS ": "3",
        course: "ไทย",
        keywords: "มธ. TU ทาม ไทม์ time",
    },
    {
        number: "9",
        studentID: "54632",
        name: "ชัชพล",
        sirname: "บุญยัง",
        university: "มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี",
        faculty: "วิศวกรรมศาสตร์",
        major: "วิศวกรรมเครื่องกล",
        "TCAS ": "1",
        course: "ไทย",
        keywords: "ลูกหมู lookmhu มจธ. kmutt บางมด วิศวะ",
    },
    {
        number: "10",
        studentID: "54634",
        name: "ปวริศร์",
        sirname: "คลังเงิน",
        university: "ศรีนครินทรวิโรฒ",
        faculty: "เภสัชศาสตร์",
        major: "-",
        "TCAS ": "3",
        course: "ไทย",
        keywords: "หม่อน มศว. SWU",
    },
    {
        number: "11",
        studentID: "54640",
        name: "ธนภัทร",
        sirname: "สัจจปาละ",
        university: "วิทยาลัยแพทยศาสตร์พระมงกุฎเกล้า",
        faculty: "แพทยศาสตร์",
        major: "-",
        "TCAS ": "3",
        course: "ไทย",
        keywords: "ช็อป ชอป shop หมอ วพม. PCM แพทย์ เเพทยศาสตร์ เเพทย์",
    },
    {
        number: "12",
        studentID: "54645",
        name: "พฤต",
        sirname: "นีระพันธุ์",
        university: "จุฬาลงกรณ์มหาวิทยาลัย",
        faculty: "เทคนิคการแพทย์",
        major: "-",
        "TCAS ": "3",
        course: "ไทย",
        keywords: "พี p cu chula",
    },
    {
        number: "13",
        studentID: "54652",
        name: "กันตินันท์",
        sirname: "แสงประชาธนารักษ์",
        university: "จุฬาลงกรณ์มหาวิทยาลัย",
        faculty: "International School of Engineering",
        major: "Automotive Design and Manufacturing Engineering (Adme)",
        "TCAS ": "1",
        course: "นานาชาติ",
        keywords: "อินเตอร์ วิศวะ CU chula เอเบิล เอเบิ้ล able ISE Adme inter อินเตอร์",
    },
    {
        number: "14",
        studentID: "54653",
        name: "ปัณณพัฒน์",
        sirname: "เกตุแก้ว",
        university: "มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี",
        faculty: "สถาบันวิทยาการหุ่นยนต์ภาคสนาม (FIBO)",
        major: "วิศวกรรมหุ่นยนต์และระบบอัตโนมัติ",
        "TCAS ": "2",
        course: "ไทย",
        keywords: "บางมด วิศวะ KMUTT ปั้น fibo pun มจธ.",
    },
    {
        number: "15",
        studentID: "54655",
        name: "ณัฐดนัย",
        sirname: "เขียนสา",
        university: "วิทยาลัยแพทยศาสตร์พระมงกุฎเกล้า",
        faculty: "แพทยศาสตร์",
        major: "-",
        "TCAS ": "3",
        course: "ไทย",
        keywords: "mickie มิคกี้ มิกกี้ micky หมอ วพม. PCM เเพทยศาสตร์ เเพทย์ แพทย์",
    },
    {
        number: "16",
        studentID: "54666",
        name: "อธิวัฒน์",
        sirname: "พัสระ",
        university: "จุฬาลงกรณ์มหาวิทยาลัย",
        faculty: "International School of Engineering",
        major: "Information and Communication Engineering (ICE)",
        "TCAS ": "1",
        course: "นานาชาติ",
        keywords: "อินเตอร์ วิศวะ CU chula พี P ISE ICE พีแว่นเขียว inter อินเตอร์",
    },
    {
        number: "17",
        studentID: "54670",
        name: "นลธวัช",
        sirname: "กัลยาวุฒิพงศ์",
        university: "มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี",
        faculty: "วิศวกรรมศาสตร์",
        major: "วิศวกรรมคอมพิวเตอร์",
        "TCAS ": "3",
        course: "ไทย",
        keywords: "mix xim มิกซ์ วิศวะคอม มจธ. บางมด kmutt",
    },
    {
        number: "18",
        studentID: "54675",
        name: "ชยาทิตย์",
        sirname: "ปั้นศิริ",
        university: "มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี",
        faculty: "วิศวกรรมศาสตร์",
        major: "วิศวกรรมเครื่องกล",
        "TCAS ": "1",
        course: "ไทย",
        keywords: "พลับ plub มจธ. kmutt บางมด วิศวะ",
    },
    {
        number: "19",
        studentID: "54676",
        name: "สุหฤท",
        sirname: "สนใจพาณิชย์",
        university: "จุฬาลงกรณ์มหาวิทยาลัย",
        faculty: "นิติศาสตร์",
        major: "-",
        "TCAS ": "3.1",
        course: "ไทย",
        keywords: "แบง bang CU chula",
    },
    {
        number: "20",
        studentID: "54691",
        name: "วันเลิศ",
        sirname: "นาวีพัฒนา",
        university: "มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี",
        faculty: "วิศวกรรมศาสตร์",
        major: "วิศวกรรมเคมี",
        "TCAS ": "1",
        course: "ไทย",
        keywords: "ต้า ta วิศวะเคมี มจธ. บางมด kmutt",
    },
    {
        number: "21",
        studentID: "54698",
        name: "ณัฏฐกนต์",
        sirname: "ภานุปภาพร",
        university: "มหาวิทยาลัยสงขลานครินทร์",
        faculty: "ทันตแพทย์ศาสตร์",
        major: "-",
        "TCAS ": "3",
        course: "ไทย",
        keywords: "หมีภู หมีพูห์ pooh มอ. PSU ทันตะ",
    },
    {
        number: "22",
        studentID: "54700",
        name: "มาศนิธิศ",
        sirname: "จริยเศรษฐพงศ์",
        university: "จุฬาลงกรณ์มหาวิทยาลัย",
        faculty: "วิศวกรรมศาสตร์",
        major: "ทั่วไป",
        "TCAS ": "3",
        course: "ไทย",
        keywords: "เจมส์ james วิศวะรวม วิศวะทั่วไป Chula CU",
    },
    {
        number: "23",
        studentID: "54701",
        name: "มาศนิวิฐ",
        sirname: "จริยเศรษฐพงศ์",
        university: "จุฬาลงกรณ์มหาวิทยาลัย",
        faculty: "วิศวกรรมศาสตร์",
        major: "วิศวกรรมทั่วไป",
        "TCAS ": "3",
        course: "ไทย",
        keywords: "วิศวะ Chula CU หลุยส์ louise วิศวะรวม วิศวะทั่วไป",
    },
    {
        number: "24",
        studentID: "54716",
        name: "ณภัทร์",
        sirname: "จันทร์สัชนาลัย",
        university: "มหาวิทยาลัยเชียงใหม่",
        faculty: "แพทยศาสตร์",
        major: "-",
        "TCAS ": "3",
        course: "ไทย",
        keywords: "นด ณศ nod มช. หมอ แพทย์ เเพทยศาสตร์ เเพทย์",
    },
    {
        number: "25",
        studentID: "54733",
        name: "นทีเทพ",
        sirname: "สุขพืชกิจ",
        university: "จุฬาลงกรณ์มหาวิทยาลัย",
        faculty: "วิศวกรรมศาสตร์",
        major: "วิศวกรรมทั่วไป",
        "TCAS ": "3",
        course: "ไทย",
        keywords: "แม๊ป map วิศวะ Chula CU วิศวะรวม วิศวะทั่วไป",
    },
    {
        number: "26",
        studentID: "54736",
        name: "พศิณ",
        sirname: "รัตนจงกล",
        university: "จุฬาลงกรณ์มหาวิทยาลัย",
        faculty: "แพทยศาสตร์",
        major: "-",
        "TCAS ": "3",
        course: "ไทย",
        keywords: "ภึม peem เเพทยศาสตร์ เเพทย์ แพทย์ หมอ",
    },
    {
        number: "27",
        studentID: "54737",
        name: "ลัทธวัฒน์",
        sirname: "ทนินซ้อน",
        university: "วิทยาลัยแพทยศาสตร์พระมงกุฎเกล้า",
        faculty: "แพทยศาสตร์",
        major: "-",
        "TCAS ": "3",
        course: "ไทย",
        keywords: "ใบบุญ baiboon เเพทยศาสตร์ เเพทย์ แพทย์ หมอ",
    },
    {
        number: "28",
        studentID: "54739",
        name: "พุฒิเมธ",
        sirname: "สละกลม",
        university: "มหาวิทยาลัยศรีนครินทรวิโรฒ",
        faculty: "แพทยศาสตร์",
        major: "-",
        "TCAS ": "3",
        course: "ไทย",
        keywords: "เต็ม tem มศว. SWU แพทย์ หมอ เเพทยศาสตร์ เเพทย์",
    },
    {
        number: "29",
        studentID: "54748",
        name: "รัชชานนท์",
        sirname: "จันทร์เปรมปรี",
        university: "มหาวิทยาลัยมหิดล",
        faculty: "แพทยศาสตร์ศิริราชพยาบาล",
        major: "สาขาวิชาการแพทย์แผนไทยประยุกต์",
        "TCAS ": "3",
        course: "ไทย",
        keywords: "แพทย์ นนท์ nont MU หมอ เเพทยศาสตร์ เเพทย์",
    },
    {
        number: "30",
        studentID: "54750",
        name: "กฤตพจน์",
        sirname: "แสงประชาธนารักษ์",
        university: "จุฬาลงกรณ์มหาวิทยาลัย",
        faculty: "International School of Engineering",
        major: "Information and Communication Engineering (ICE)",
        "TCAS ": "1",
        course: "นานาชาติ",
        keywords: "zno ซีโน่ ISE CU chula ICE วิศวะ inter อินเตอร์",
    },
    {
        number: "31",
        studentID: "54754",
        name: "ณัฐวัสส์",
        sirname: "ตรงศิริวัฒน์",
        university: "จุฬาลงกรณ์มหาวิทยาลัย",
        faculty: "วิศวกรรมศาสตร์",
        major: "วิศวกรรมทั่วไป",
        "TCAS ": "3",
        course: "ไทย",
        keywords: "oak o4k โอ๊ค วิศวะ CU chula วิศวะรวม วิศวะทั่วไป",
    },
    {
        number: "32",
        studentID: "54765",
        name: "ณพวิทย์",
        sirname: "รัตนวารินทร์ชัย",
        university: "จุฬาลงกรณ์มหาวิทยาลัย",
        faculty: "สถาปัตยกรรมศาสตร์",
        major: "สถาปัตยกรรมไทย",
        "TCAS ": "2",
        course: "ไทย",
        keywords: "ป้อง pong สถาปัตย์ สถาปัตย์ไทย",
    },
    {
        number: "33",
        studentID: "54766",
        name: "ศาสตรา",
        sirname: "กัตตเวทีวงศ์",
        university: "จุฬาลงกรณ์มหาวิทยาลัย",
        faculty: "สัตวแพทยศาสตร์",
        major: "-",
        "TCAS ": "3",
        course: "ไทย",
        keywords: "กี้ kee สัตวแพทย์ สัตวเเพทยศาสตร์ สัตวเเพทย์",
    },
    {
        number: "34",
        studentID: "54775",
        name: "ธนกร",
        sirname: "ทองสิมา",
        university: "มหาวิทยาลัยมหิดล",
        faculty: "เทคนิคการแพทย์",
        major: "-",
        "TCAS ": "3",
        course: "ไทย",
        keywords: "กร popkorn MU มม. เทคนิคการเเพทย์",
    },
    {
        number: "35",
        studentID: "54799",
        name: "ปรีชาพล",
        sirname: "ฤดีอเนกสิน",
        university: "มหาวิทยาลัยเกษตรศาสตร์",
        faculty: "วิศวกรรมศาสตร์",
        major: "วิศวกรรมโยธา",
        "TCAS ": "",
        course: "",
        keywords: "โชกุน shogun วิศวะโยธา มก. KU",
    },
    {
        number: "36",
        studentID: "54804",
        name: "กันต์",
        sirname: "ตันติกนกพร",
        university: "มหาวิทยาลัยศรีนครินทรวิโรฒ",
        faculty: "ทันตแพทยศาสตร์",
        major: "-",
        "TCAS ": "3",
        course: "",
        keywords: "gunt มศว swu ทันตะ",
    },
    {
        number: "37",
        studentID: "54806",
        name: "ปุณณวิช",
        sirname: "นำแสงวาณิช",
        university: "จุฬาลงกรณ์มหาวิทยาลัย",
        faculty: "วิศวกรรมศาสตร์",
        major: "วิศวกรรมทั่วไป",
        "TCAS ": "3",
        course: "ไทย",
        keywords: "วิศวะ Chula CU ปั้น pun วิศวะรวม วิศวะทั่วไป",
    },
    {
        number: "38",
        studentID: "54808",
        name: "วุฒิภัทร",
        sirname: "ถนอมเจริญ",
        university: "จุฬาลงกรณ์มหาวิทยาลัย",
        faculty: "แพทยศาสตร์",
        major: "แพทยศาสตร์กองทัพอากาศ",
        "TCAS ": "3",
        course: "ไทย",
        keywords: "beckham เบ็คแฮม Chula CU หมอ แพทย์ เเพทยศาสตร์ เเพทย์",
    },
    {
        number: "39",
        studentID: "54814",
        name: "พัทธพล",
        sirname: "ฐาปนพงศ์พันธุ์",
        university: "มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี",
        faculty: "วิศวกรรมศาสตร์",
        major: "เครื่องกล",
        "TCAS ": "1",
        course: "ไทย",
        keywords: "วิศวะ มจธ. บางมด kmutt บุ๋น bun",
    },
    {
        number: "40",
        studentID: "54844",
        name: "กนธี",
        sirname: "สุขเกื้อ",
        university: "จุฬาลงกรณ์มหาวิทยาลัย",
        faculty: "เภสัชศาสตร์",
        major: "วิชาการบริบาลทางเภสัชกรรม",
        "TCAS ": "3",
        course: "ไทย",
        keywords: "ปูม poom Chula CU",
    },
    {
        number: "41",
        studentID: "54871",
        name: "ภคิน",
        sirname: "พุทธนุกูลชัย",
        university: "จุฬาลงกรณ์มหาวิทยาลัย",
        faculty: "วิศวกรรมศาสตร์",
        major: "วิศวกรรมทั่วไป",
        "TCAS ": "3",
        course: "ไทย",
        keywords: "ไบร์ท onfirebyte bright pakin วิศวะ Chula CU  วิศวะรวม วิศวะทั่วไป",
    },
    {
        number: "42",
        studentID: "54888",
        name: "อิทธิวัฒน์",
        sirname: "ว่องกิตติพงษ์",
        university: "จุฬาลงกรณ์มหาวิทยาลัย",
        faculty: "เศรษฐศาสตร์",
        major: "เศรษฐศาสตร์",
        "TCAS ": "3",
        course: "ไทย",
        keywords: "Chula CU เซฟ safe save ",
    },
    {
        number: "43",
        studentID: "55029",
        name: "ธนภูมิ",
        sirname: "รอดขำ",
        university: "จุฬาลงกรณ์มหาวิทยาลัย",
        faculty: "ภูมิสถาปัตยกรรม",
        major: "-",
        "TCAS ": "",
        course: "ไทย",
        keywords: "กฤต กิต กิด krit ภูมิสถาปัตย์ cu chula",
    },
];
